services:
  db:
    image: postgres:17.2-bookworm
    volumes:
      - type: bind
        source: ./dev-db
        target: /var/lib/postgresql/data/
    user: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 1s
      retries: 10
  django:
    build:
      target: dev
    container_name: django
    volumes:
      - type: bind
        source: .
        target: /django/
    depends_on:
      db:
        condition: service_healthy
    tty: true
    ports:
      - 3000:3000
