services:
  frontend:
    build:
      context: frontend
      target: prod
    container_name: frontend
    ports:
      - 25000:25000
    environment:
      PORT: 25000
    depends_on:
      db:
        condition: service_healthy
    tty: true
  backend:
    build:
      context: backend
      target: prod
    container_name: backend
    env_file: ./backend/.env
    depends_on:
      db:
        condition: service_healthy
    tty: true
  db:
    image: postgres:17.2-bookworm
    container_name: db
    volumes:
      - type: volume
        source: prod_mc_recipes_db
        target: /var/lib/postgresql/data/
      # - type: bind
      #   source: ./backend/migrations
      #   target: /docker-entrypoint-initdb.d
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 1s
      retries: 10

volumes:
  prod_mc_recipes_db:
