services:
  django:
    build:
      target: prod
    container_name: django
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    tty: true
    ports:
      - 25000:3000
  db:
    image: postgres:17.2-bookworm
    container_name: db
    user: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 1s
      retries: 10
