services:
  db:
    image: postgres:17.2-bookworm
    volumes:
      - type: bind
        source: ./dev-db
        target: /var/lib/postgresql/data/
    user: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 1s
      retries: 10
  backend:
    build:
      target: dev
    container_name: backend
    volumes:
      - type: bind
        source: ./api
        target: /api
    depends_on:
      db:
        condition: service_healthy
    tty: true
